apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessMode:
    - ReadWriteOnce:
  resources:
    requests:
      storage: 2Gi
  storageClassName: default